### ISSUE TITLE
Crash on Linux because asset not found

### ISSUE THREAD

**Issue by staadecker** [krsh2001/Hackerman-executable#2]
Program crashes when you try to "hack" the first button of the game. Throws an error saying that `ROMunselected.png` is not found (in `Assets/Minigame/HardwareQuiz`). This is because the file is named `romunselected.png` not `ROMunselected.png` without the uppercase ROM. Renaming the file fixes the issue. The same must be done with `ROMselected.png`. Not sure about `romtexture.png`.

Might be Linux specific (running Ubuntu 18.04.01)

**Comment by staadecker** [comment]
This is the error

`Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: Assets/Minigame/HardwareQuiz/ROMunselected.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:147)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:88)
	at com.mygdx.game.HardwareQuiz.<init>(HardwareQuiz.java:56)
	at com.mygdx.game.Router.hack(Router.java:70)
	at com.mygdx.game.Player.touchDown(Player.java:291)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:329)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: Assets/Minigame/HardwareQuiz/ROMunselected.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
	... 10 more
`
